apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Register build artifact
        id: register-artifact
        with:
          version: ${{ cloudbees.version }}
          url: docker.io/myapp/artifact:${{cloudbees.version}}
          name: artifact
        uses: cloudbees-io/register-build-artifact@v2
      - name: Print artifact ID
        uses: docker://alpine:latest
        shell: sh
        run: |
           echo "artifact ID for artifact:${{cloudbees.version}} is: ${{ steps.register-artifact.outputs.artifact-id }}"
